### PR TITLE
Fix: Better handling of paths to correctly manage windows paths from Arr

### PR DESCRIPTION
**Pull request by Feramance**

### CODE REVIEW

**Comment by Feramance** [comment]
Still testing, don't merge

**Comment by Feramance** [comment]
Actually fixed now. This change will allow daps to recognise and parse windows paths correctly

**Comment by Drazzilb08** [comment]
I'll merge this when I get a chance to look it all over. Prolly gonna be this weekend when I actually get to it. 

I assume this has also been tested on a Linux machine as well to make sure no bugs were introduced?

**Comment by Feramance** [comment]
Yes it has, and it just uses a regex match to recognise a Windows drive path which will never be the case on Linux

**Comment by Feramance** [comment]
Any updates on this please?

**Pull request merged**
